apiVersion: v2
name: istio
description: Helm Charts adapted from Istio official repository
type: application
version: 1.11.1
appVersion: "1.11.1"
dependencies:
  - name: base
    version: 1.11.1
    repository: file://./istio-charts/base
  - name: istio-discovery
    version: 1.11.1
    repository: file://./istio-charts/istio-control/istio-discovery
  - name: istio-ingress
    version: 1.11.1
    repository: file://./istio-charts/gateways/istio-ingress
  - name: istio-egress
    version: 1.11.1
    repository: file://./istio-charts/gateways/istio-egress
maintainers:
  - name: getindata
    email: mlops@getindata.com
    url: https://getindata.com
